version: 2

sources:
  - name: raw
    database: wageanalysis  
    schema: raw  
    tables:
      - name: country_job_info
      - name: popular_companies
      - name: countrys
      - name: currency_exchange
      - name: country_expenses
      - name: country_expenses_detail
